spring.application.name=auth

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/authdb?schema=auth
spring.r2dbc.username=postgres
spring.r2dbc.password=15167180


server.port=8080

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql


grpc.client.account.address=static://localhost:9091
grpc.client.account.negotiationType=PLAINTEXT

grpc.client.customer.address=static://localhost:9092
grpc.client.customer.negotiationType=PLAINTEXT

