spring.application.name=authZ

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/authZdb?schema=authZ
spring.r2dbc.username=postgres
spring.r2dbc.password=15167180


server.port=8081

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql

