spring.application.name=customer

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/customerdb?schema=customer
spring.r2dbc.username=postgres
spring.r2dbc.password=15167180


server.port=8083
grpc.server.port=9092

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql




