spring.application.name=account

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/accountdb?schema=account
spring.r2dbc.username=postgres
spring.r2dbc.password=15167180


server.port=8082
grpc.server.port=9091

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql




